name: chocolatine
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NCE-2-1-chocolatine-maxime.novarese.git

on:
  push:
    branche-ignore:
      - ga-ignore-*
  pull_request:
    branche-ignore:
      - ga-ignore-*

jobs:
  check_repository_cleanliness:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          if find ./ ( -name "#*#" -o -name "*~" -o -name ".o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -path "/tmp/" -type f ) -exec false {} +
            then
              exit 0
            else
              path=$(find ./ ( -name "#*#" -o -name "*~" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -path "/tmp/" -type f ))
              for i in $path; do
                 echo "::error file=$i,line=1,endLine=1,title=Unwanted file detected::$i"
              done
              exit 1
            fi
            exit 0

  check_program_compilation:
    needs: check_repository_cleanliness
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          exit 0

  run_tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          exit 0

  push_to_mirror:
    needs: [check_program_compilation, run_tests]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
  